server:
  port: 8888
eureka:
  instance:
    prefer-ip-address: true
    metadata-map:
      lancher: 1
  client:
    service-url:
      defaultZone: http://localhost:11000/eureka/
node: "instance 1"
spring:
  application:
    name: user
