spring:
  application:
    name: yss-base-gateway
server:
  port: 7702


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:11000/eureka/
  instance:
    prefer-ip-address: true
zuul:
  routes:
    user:
      path: /user/**
      service-id: user
  host:
    socket-timeout-millis: 6000
    connect-timeout-millis: 6000
management:
  endpoints:
    web:
      exposure:
        include: '*'
